[package]
name = "fetch-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.104", default-features = false }
chrono = "0.4.45"
octocrab = "0.54.1"
serde = { version = "1.0.229", default-features = false }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23" }
